data:
  alt: 'produktlebenszyklus grafik erstellen'
  imagelink: /assets/blog/2022/produktlebenszyklus/produktlebenszyklus-beispiel-min.png
size: 23018
last_modified: 1669752930
width: 1092
height: 663
mime_type: image/png
duration: null
