data:
  alt: 'produktlebenszyklus beispiel iphone'
  imagelink: /assets/blog/2022/produktlebenszyklus/produktlebenszyklus-apple-min.png
size: 53560
last_modified: 1669752397
width: 1727
height: 957
mime_type: image/png
duration: null
