data:
  alt: 'bcg portfolio matrix: Produktlebenszyklus'
  caption: 'Produktlebenszyklus (Quelle: Eigene Darstellung)'
size: 37774
last_modified: 1663270555
width: 1505
height: 719
mime_type: image/png
duration: null
